import { validateCatalog } from './content-validation';
export const categories = ['HTML', 'CSS', 'JavaScript', 'Python'] as const;
export const levels = ['Beginner', 'Intermediate'] as const;
export type Entry = { id: number; title: string; category: string; level: string; summary: string };
export const catalog: Entry[] = [
  {
    id: 1,
    title: 'Semantic landmarks',
    category: 'HTML',
    level: 'Beginner',
    summary: 'Use main, nav, and header to communicate the purpose of page regions.',
  },
  {
    id: 2,
    title: 'Form labels',
    category: 'HTML',
    level: 'Beginner',
    summary: 'Connect each label to an input so its name is available to everyone.',
  },
  {
    id: 3,
    title: 'Image alternatives',
    category: 'HTML',
    level: 'Beginner',
    summary: 'Describe meaningful images and leave decorative images with empty alternative text.',
  },
  {
    id: 4,
    title: 'Native validation',
    category: 'HTML',
    level: 'Intermediate',
    summary:
      'Use required, min, and max to guide input while validating values again on the server.',
  },
  {
    id: 5,
    title: 'Document headings',
    category: 'HTML',
    level: 'Beginner',
    summary: 'Organize content with a clear heading hierarchy.',
  },
  {
    id: 6,
    title: 'Table structure',
    category: 'HTML',
    level: 'Intermediate',
    summary: 'Use table headers and captions to explain related rows and columns.',
  },
  {
    id: 7,
    title: 'Flexbox alignment',
    category: 'CSS',
    level: 'Beginner',
    summary: 'Align items along a main axis and a cross axis.',
  },
  {
    id: 8,
    title: 'Grid tracks',
    category: 'CSS',
    level: 'Intermediate',
    summary: 'Define rows and columns for a two-dimensional layout.',
  },
  {
    id: 9,
    title: 'Responsive layouts',
    category: 'CSS',
    level: 'Intermediate',
    summary: 'Use media queries to adapt a layout without hiding essential content.',
  },
  {
    id: 10,
    title: 'Visible focus',
    category: 'CSS',
    level: 'Beginner',
    summary: 'Keep keyboard focus visible with a clear outline.',
  },
  {
    id: 11,
    title: 'Box sizing',
    category: 'CSS',
    level: 'Beginner',
    summary: 'Use border-box to include padding and borders in declared dimensions.',
  },
  {
    id: 12,
    title: 'Print styles',
    category: 'CSS',
    level: 'Intermediate',
    summary: 'Hide editing controls and simplify spacing for printed output.',
  },
  {
    id: 13,
    title: 'Array filtering',
    category: 'JavaScript',
    level: 'Beginner',
    summary: 'Create a subset of an array by testing each item with a predicate.',
  },
  {
    id: 14,
    title: 'Event listeners',
    category: 'JavaScript',
    level: 'Beginner',
    summary: 'Connect user actions to small functions with addEventListener.',
  },
  {
    id: 15,
    title: 'Promise errors',
    category: 'JavaScript',
    level: 'Intermediate',
    summary: 'Handle rejected promises with catch or try and catch around await.',
  },
  {
    id: 16,
    title: 'URL parameters',
    category: 'JavaScript',
    level: 'Intermediate',
    summary: 'Use URLSearchParams to encode and read query-string values.',
  },
  {
    id: 17,
    title: 'Integer cents',
    category: 'JavaScript',
    level: 'Intermediate',
    summary: 'Represent fixed-precision prices with integer cents before calculating totals.',
  },
  {
    id: 18,
    title: 'Safe text rendering',
    category: 'JavaScript',
    level: 'Beginner',
    summary: 'Use textContent to display untrusted text without interpreting it as markup.',
  },
  {
    id: 19,
    title: 'Dictionary lookups',
    category: 'Python',
    level: 'Beginner',
    summary: 'Map keys to values and handle missing keys explicitly.',
  },
  {
    id: 20,
    title: 'Context managers',
    category: 'Python',
    level: 'Intermediate',
    summary: 'Use with to close files even when an operation fails.',
  },
  {
    id: 21,
    title: 'CSV reading',
    category: 'Python',
    level: 'Beginner',
    summary: 'Use the csv module to respect delimiters and quoted fields.',
  },
  {
    id: 22,
    title: 'Argument parsing',
    category: 'Python',
    level: 'Intermediate',
    summary: 'Use argparse to define a command-line interface and validate options.',
  },
  {
    id: 23,
    title: 'Unit tests',
    category: 'Python',
    level: 'Intermediate',
    summary: 'Exercise normal behavior and boundary cases with isolated inputs.',
  },
  {
    id: 24,
    title: 'Path handling',
    category: 'Python',
    level: 'Beginner',
    summary: 'Use pathlib to work with file paths without manual separator concatenation.',
  },
];

validateCatalog(catalog, categories, levels);
